import type { Metadata } from "next";
import UserLayout from "./layout/UserLayout";

export const metadata: Metadata = {
  title: "Recipe Sharing Community",
  description: "Generated by @KJ-RahiiL",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <UserLayout>{children}</UserLayout>
    </div>
  );
}